# Generated by Django 4.2 on 2023-05-24 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='file',
        ),
        migrations.AddField(
            model_name='file',
            name='file12',
            field=models.FileField(default=2, upload_to=''),
            preserve_default=False,
        ),
    ]
