# Generated by Django 4.2 on 2023-05-24 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_file_file_file_file12'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='file12',
            new_name='file',
        ),
    ]
