# Generated by Django 4.2 on 2023-06-02 16:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_file_file_course_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='stydent_course_fee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_fee', models.CharField(max_length=300)),
                ('paid_amount', models.CharField(max_length=300)),
                ('selected_course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.course')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
