# Generated by Django 4.2 on 2023-06-03 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_newuser_user_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='stydent_course_fee',
            new_name='student_course_fee',
        ),
    ]
