# Generated by Django 4.2 on 2023-06-11 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_rename_student_id_student_course_fee_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_course_fee',
            name='remaining_fee',
            field=models.FloatField(default=0.0),
        ),
    ]
