# Generated by Django 4.2 on 2023-06-11 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_student_course_fee_remaining_fee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student_course_fee',
            name='remaining_fee',
        ),
    ]
